/**
 * contracts.ts — Contract ABIs and address helpers
 *
 * Minimal ABIs include only the functions used by the frontend.
 * Full ABIs are generated by Hardhat TypeChain into contracts/typechain-types/.
 */

// ─── Contract Addresses ───────────────────────────────────────────────────────

export const CONTRACT_ADDRESSES = {
  agentRegistry:    (process.env.NEXT_PUBLIC_AGENT_REGISTRY    ?? "") as `0x${string}`,
  jobRegistry:      (process.env.NEXT_PUBLIC_JOB_REGISTRY      ?? "") as `0x${string}`,
  reputationOracle: (process.env.NEXT_PUBLIC_REPUTATION_ORACLE ?? "") as `0x${string}`,
  marketplace:      (process.env.NEXT_PUBLIC_MARKETPLACE       ?? "") as `0x${string}`,
  usdc:             (process.env.NEXT_PUBLIC_USDC ?? "0x3600000000000000000000000000000000000000") as `0x${string}`,
} as const;

// ─── AgentRegistry ABI ────────────────────────────────────────────────────────

export const AGENT_REGISTRY_ABI = [
  // Write
  {
    name: "registerAgent",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "name", type: "string" }, { name: "skills", type: "string[]" }],
    outputs: [{ name: "agentId", type: "bytes32" }],
  },
  {
    name: "setAgentURI",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "agentId", type: "bytes32" }, { name: "newURI", type: "string" }],
    outputs: [],
  },
  // Read
  {
    name: "getAgent",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "agentId", type: "bytes32" }],
    outputs: [{
      type: "tuple",
      components: [
        { name: "agentId",          type: "bytes32"   },
        { name: "wallet",           type: "address"   },
        { name: "name",             type: "string"    },
        { name: "skills",           type: "string[]"  },
        { name: "agentURI",         type: "string"    },
        { name: "reputationScore",  type: "uint256"   },
        { name: "jobsCompleted",    type: "uint256"   },
        { name: "verified",         type: "bool"      },
        { name: "createdAt",        type: "uint256"   },
      ],
    }],
  },
  {
    name: "getAgentByWallet",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "wallet", type: "address" }],
    outputs: [{
      type: "tuple",
      components: [
        { name: "agentId",          type: "bytes32"   },
        { name: "wallet",           type: "address"   },
        { name: "name",             type: "string"    },
        { name: "skills",           type: "string[]"  },
        { name: "agentURI",         type: "string"    },
        { name: "reputationScore",  type: "uint256"   },
        { name: "jobsCompleted",    type: "uint256"   },
        { name: "verified",         type: "bool"      },
        { name: "createdAt",        type: "uint256"   },
      ],
    }],
  },
  // Events
  {
    name: "AgentRegistered",
    type: "event",
    inputs: [
      { name: "agentId", type: "bytes32", indexed: true  },
      { name: "wallet",  type: "address", indexed: true  },
      { name: "name",    type: "string",  indexed: false },
    ],
  },
] as const;

// ─── JobRegistry ABI ─────────────────────────────────────────────────────────

export const JOB_REGISTRY_ABI = [
  // Write
  {
    name: "createJob",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "title",          type: "string"   },
      { name: "description",    type: "string"   },
      { name: "requiredSkills", type: "string[]" },
      { name: "budget",         type: "uint256"  },
      { name: "deadline",       type: "uint256"  },
      { name: "jobURI",         type: "string"   },
    ],
    outputs: [{ name: "jobId", type: "bytes32" }],
  },
  {
    name: "applyForJob",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "jobId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "assignAgent",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "jobId", type: "bytes32" }, { name: "agentId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "startJob",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "jobId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "submitDeliverable",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "jobId", type: "bytes32" }, { name: "deliverableURI", type: "string" }],
    outputs: [],
  },
  {
    name: "approveWork",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId",              type: "bytes32" },
      { name: "satisfactionScore",  type: "uint8"   },
      { name: "feedbackComment",    type: "string"  },
    ],
    outputs: [],
  },
  {
    name: "requestRevision",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "jobId", type: "bytes32" }, { name: "feedback", type: "string" }],
    outputs: [],
  },
  {
    name: "cancelJob",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "jobId", type: "bytes32" }],
    outputs: [],
  },
  // Read
  {
    name: "getJob",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "jobId", type: "bytes32" }],
    outputs: [{
      type: "tuple",
      components: [
        { name: "jobId",          type: "bytes32"  },
        { name: "employer",       type: "address"  },
        { name: "assignedAgent",  type: "bytes32"  },
        { name: "title",          type: "string"   },
        { name: "description",    type: "string"   },
        { name: "requiredSkills", type: "string[]" },
        { name: "budget",         type: "uint256"  },
        { name: "deadline",       type: "uint256"  },
        { name: "status",         type: "uint8"    },
        { name: "deliverableURI", type: "string"   },
        { name: "jobURI",         type: "string"   },
        { name: "platformFee",    type: "uint256"  },
        { name: "createdAt",      type: "uint256"  },
        { name: "completedAt",    type: "uint256"  },
      ],
    }],
  },
  {
    name: "getApplications",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "jobId", type: "bytes32" }],
    outputs: [{ type: "bytes32[]" }],
  },
  {
    name: "getEmployerJobs",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "employer", type: "address" }],
    outputs: [{ type: "bytes32[]" }],
  },
  {
    name: "getAgentJobs",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "agentId", type: "bytes32" }],
    outputs: [{ type: "bytes32[]" }],
  },
  {
    name: "platformFeeBps",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "totalVolumeUsdc",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ type: "uint256" }],
  },
  // Events
  {
    name: "JobCreated",
    type: "event",
    inputs: [
      { name: "jobId",    type: "bytes32", indexed: true  },
      { name: "employer", type: "address", indexed: true  },
      { name: "budget",   type: "uint256", indexed: false },
      { name: "title",    type: "string",  indexed: false },
    ],
  },
  {
    name: "JobCompleted",
    type: "event",
    inputs: [
      { name: "jobId",          type: "bytes32", indexed: true  },
      { name: "agentId",        type: "bytes32", indexed: true  },
      { name: "agentPayment",   type: "uint256", indexed: false },
      { name: "platformFee",    type: "uint256", indexed: false },
    ],
  },
] as const;

// ─── USDC ABI (minimal ERC-20) ────────────────────────────────────────────────

export const USDC_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ type: "uint8" }],
  },
] as const;

// ─── Marketplace ABI ─────────────────────────────────────────────────────────

export const MARKETPLACE_ABI = [
  {
    name: "getAddresses",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{
      type: "tuple",
      components: [
        { name: "agentRegistry",   type: "address" },
        { name: "jobRegistry",     type: "address" },
        { name: "reputationOracle",type: "address" },
        { name: "usdc",            type: "address" },
      ],
    }],
  },
  {
    name: "getPlatformStats",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{
      type: "tuple",
      components: [
        { name: "totalJobs",       type: "uint256" },
        { name: "openJobs",        type: "uint256" },
        { name: "completedJobs",   type: "uint256" },
        { name: "disputedJobs",    type: "uint256" },
        { name: "totalAgents",     type: "uint256" },
        { name: "verifiedAgents",  type: "uint256" },
        { name: "totalVolumeUsdc", type: "uint256" },
        { name: "totalFeesCollected", type: "uint256" },
        { name: "lastUpdated",     type: "uint256" },
      ],
    }],
  },
  {
    name: "getFeaturedAgents",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{
      type: "tuple[]",
      components: [
        { name: "agentId",      type: "bytes32" },
        { name: "featuredUntil",type: "uint256" },
        { name: "tagline",      type: "string"  },
      ],
    }],
  },
  {
    name: "getFeaturedJobs",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{
      type: "tuple[]",
      components: [
        { name: "jobId",        type: "bytes32" },
        { name: "featuredUntil",type: "uint256" },
      ],
    }],
  },
] as const;

// ─── Job Status enum ──────────────────────────────────────────────────────────

export const JOB_STATUS = {
  0: "Open",
  1: "Assigned",
  2: "In Progress",
  3: "Submitted",
  4: "Completed",
  5: "Disputed",
  6: "Resolved",
  7: "Cancelled",
} as const;

export type JobStatusNumber = keyof typeof JOB_STATUS;
